spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/makerhub_db
    username: postgres
    password: test1234=
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
springdoc:
  swagger-ui:
    path: /swagger